### ISSUE TITLE
Keyboard shortcut doesn't work for en_US

### ISSUE THREAD

**Issue by DanGoldwater** [brunnerh/altervista-thesaurus#1]
I've posted this as a question over [SuperUser](https://superuser.com/questions/1481076/how-can-i-make-the-key-binding-work-for-the-thesaurus-extension-in-vscode) - but here might be more appropriate. 
I'm using VSCode on Windows 10. I use a thesaurus a lot when I write, so I was delighted to find this extension for VSC. I've installed it and it almost works fine.

When I run the command Altervisa Thesaurus: Synonyms from pressing `Ctrl+p`, I get a good list of words for whatever I search for. I added the recommended key-binding to my settings.json file:

`"key": "ctrl+l g",
        "command": "altervista-thesaurus.synonyms",
        "args": "de_DE"`, 
and this now also works: if I press `Ctrl+l` and then type a German word, I get a list of suggestions. However, if I change the above language key from de_DE to en_US, the search finds nothing.

The thing is the thesaurus works fine (in English) from the the Ctrl+p box, and the keyboard shortcut works fine in German. What am I missing?

**Comment by brunnerh** [comment]
@DanGoldwater With that key binding `Ctrl+l` on its own should not invoke the command at all, it would have to be followed by the `g` key. (Maybe you just failed to mention this, of course.)

A key binding with `en_US` works just fine for me. Note that i would recommend setting up a primary language via the `altervista-thesaurus.lang` setting (it defaults to `en_US`), then you can just bind the command without the `args`.

I personally have two bindings set up like this:

```json
{
	"key": "ctrl+l g",
	"command": "altervista-thesaurus.synonyms",
	"args": "de_DE"
},
{
	"key": "ctrl+l l",
	"command": "altervista-thesaurus.synonyms"
},
```

**Comment by DanGoldwater** [comment]
Thanks for your very rapid and helpful response. 

The error was entirely my own, I'm new to VSCode and I'd assumed that the key bindings went in the settings.json file, not understanding that they had their own file. 

Now resolved!
