### ISSUE TITLE
Support new lanuages

### ISSUE THREAD

**Issue by Papooch** [brunnerh/altervista-thesaurus#2]
New languages have been since added to the service, please add them in the extension as well. Though I can put the "unsupported" language explicitly in the json configuration and it works, I can't invoke the command with it from the command line.

**Comment by brunnerh** [comment]
To add:
- cs_CZ
- da_DK
- de_CH
- hu_HU
- pl_PL

**Comment by brunnerh** [comment]
Added in v.0.2.0.
