### ISSUE TITLE
Right click on a word

### ISSUE THREAD

**Issue by badetitou** [brunnerh/altervista-thesaurus#3]
Hi, 

It would be super cool if we can right-click on a word, and ask for a synonym in the contextual menu.

**Comment by brunnerh** [comment]
I looked at the code and there already are context menu entries which use the regular commands. That means that having the cursor within a word does not count as a selection.

Do you consider it much trouble to select the word first (e.g. by double clicking it)?

If I were to change how this behaves it would potentially be unexpected behavior for other users.

**Comment by badetitou** [comment]
Thanks for your super quick answer!

> Do you consider it much trouble to select the word first (e.g. by double clicking it)?

It is ok for me! I

I agree, we should not introduce unexpected behavior!

**Comment by brunnerh** [comment]
Then I will close this for now. If there is more demand for this I will reconsider it.
