### ISSUE TITLE
popup Error

### ISSUE THREAD

**Issue by bonnebulle** [brunnerh/altervista-thesaurus#7]
Hello
I just register a Key (https://thesaurus.altervista.org/mykey)
Setting up in VSC
```
    "altervista-thesaurus.lang": "fr_FR",
    "altervista-thesaurus.key": "XXXXX"
```
I have this message error :
![Screenshot_2023-02-17_14-10-07](https://user-images.githubusercontent.com/1598041/219661741-40a93738-eb3c-4dd7-8b80-8d329880ba05.png)

Can you help me finding how to "debug" this ?
Thanks

**Comment by brunnerh** [comment]
You can execute the command `Developer: Toggle Developer Tools` and check the "Console" tab for errors.

The extension works in VS Code but apparently not in VSCodium. I just installed it (v.1.75.1) and checked what happens and apparently the dependency `node-fetch` is not correctly installed or not found.

The error I get is:
> workbench.desktop.main.js:2026 Activating extension 'brunnerh.altervista-thesaurus' failed: Cannot find module 'node-fetch'
> Require stack:
> - c:\Users\brunnerh\.vscode-oss\extensions\brunnerh.altervista-thesaurus-0.2.0-universal\out\extension.js
> - c:\Program Files\VSCodium\resources\app\out\vs\loader.js
> - c:\Program Files\VSCodium\resources\app\out\bootstrap-amd.js
> - c:\Program Files\VSCodium\resources\app\out\bootstrap-fork.js.

**Comment by brunnerh** [comment]
Can you upgrade to v.0.2.1 and check whether that version works?

**Comment by bonnebulle** [comment]
I don't know what you do... but it works, thanks :)
